# DO NOT EDIT THIS FILE!
#
# This file is generated from the CDP specification. If you need to make
# changes, edit the generator and regenerate all of the modules.
#
# Specification verion: 1.3
#
#
# CDP domain: DeviceOrientation (experimental)

from __future__ import annotations

import typing


if typing.TYPE_CHECKING:
    from collections.abc import Generator

    from .util import T_JSON_DICT


def clear_device_orientation_override() -> Generator[T_JSON_DICT, T_JSON_DICT]:
    """
    Clears the overridden Device Orientation.
    :returns: A generator
    :rtype: Generator[T_JSON_DICT, T_JSON_DICT]
    """

    cmd_dict: T_JSON_DICT = {
        'method': 'DeviceOrientation.clearDeviceOrientationOverride',
    }
    json = yield cmd_dict


def set_device_orientation_override(
    alpha: float,
    beta: float,
    gamma: float,
) -> Generator[T_JSON_DICT, T_JSON_DICT]:
    """
    Overrides the Device Orientation.

    :param alpha: Mock alpha
    :param beta: Mock beta
    :param gamma: Mock gamma
    :returns: A generator
    :rtype: Generator[T_JSON_DICT, T_JSON_DICT]
    """

    params: T_JSON_DICT = {}
    params['alpha'] = alpha
    params['beta'] = beta
    params['gamma'] = gamma
    cmd_dict: T_JSON_DICT = {
        'method': 'DeviceOrientation.setDeviceOrientationOverride',
        'params': params,
    }
    json = yield cmd_dict
